import NextAuthProvider from "@/Providers/NextAuthProvider";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <body className="font-Poppins min-h-[100svh]">{children}</body>
      </NextAuthProvider>
    </html>
  );
}
