import NextAuthProvider from "@/Providers/NextAuthProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <body className=" bg-gradient-to-b from-orange-900/25 to-[30rem]  font-Poppins">
          <Toaster position="top-center" />
          {children}
        </body>
      </NextAuthProvider>
    </html>
  );
}
