import NextAuthProvider from "@/Providers/NextAuthProvider";
import "../globals.css";
import type { Metadata } from "next";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <NextAuthProvider>
      <section className="font-Poppins min-h-[100svh]">
        <Navbar />
        {children}
      </section>
    </NextAuthProvider>
  );
}
